version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1
        environment:
          BUNDLER_VERSION: 2.0.1
    steps:
      - checkout
      - run: |
          echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
          source $BASH_ENV
          gem install bundler
      - run: bundle install
      - run: bundle exec jekyll build

workflows:
  version: 2
  build:
    jobs:
      - build
